services:
  calc-app-main:
    container_name: calc-app-main
    image: ${ECR_REGISTRY_REPO}/${IMAGE_NAME_APP}:1.0

    ports:
      - "8083:8083"

    environment:
      FEIGN_CLIENT_CALCREPO_URL: http://calc-application-db:8081/api/v1/calcRepo

    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8083/actuator/health"]
      timeout: 10s
      interval: 5s
      retries: 5
      start_period: 10s

    restart: on-failure
    networks:
      - calc-app-main
      - calc-db


networks:
  calc-app-main:
    name: calc-app-main-network
    driver: bridge
  calc-db:
    name: calc-db-network
    external: true