{
 "title": "Application Main Dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (process_cpu_usage{instance=\"calc-app-main:8083\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de memória heap virtual",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(jvm_memory_committed_bytes{instance=\"calc-app-main:8083\", area=\"heap\"}[$__rate_interval]) * 1000)) / (sum by(instance) (jvm_memory_committed_bytes{instance=\"calc-app-main:8083\", area=\"heap\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de memória heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes{instance=\"calc-app-main:8083\", area=\"heap\"} / 1024) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg G1 Young Gen Pause duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(\n  rate(jvm_gc_pause_seconds_sum{instance=\"calc-app-main:8083\", gc=\"G1 Young Generation\"}[5m])\n  /\n  rate(jvm_gc_pause_seconds_count{instance=\"calc-app-main:8083\", gc=\"G1 Young Generation\"}[5m])\n) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "G1 Young Gen Pause (ms/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(gc) (rate(jvm_gc_pause_seconds_sum{instance=\"calc-app-main:8083\", gc=\"G1 Young Generation\"}[5m]) * 1000) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads ativas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=\"calc-app-main:8083\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"calc-app-main:8083\", status=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(http_server_requests_active_seconds_count{instance=\"calc-app-main:8083\", status=\"4..,\"}[5m])) or vector (0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Get Previous Operations Feign",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "com_application_infra_feign_getPreviousOperations_response_seconds_sum{instance=\"calc-app-main:8083\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Get Operations Feign",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "com_application_infra_feign_getOperations_response_seconds_sum{instance=\"calc-app-main:8083\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Persist Operation Feign",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "com_application_infra_feign_insert_response_seconds_sum{instance=\"calc-app-main:8083\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests / second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_count{instance=\"calc-app-main:8083\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Get Operations - FAILED / SUCCESS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_application_infra_feign_getOperations_total{instance=\"calc-app-main:8083\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Inserts - FAILED / SUCCESS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_application_operationService_insertOperations_total{instance=\"calc-application-db:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Get Previous Operations - FAILED / SUCCESS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_application_infra_feign_getPreviousOperations_total{instance=\"calc-app-main:8083\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application UP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"calc-app-main:8083\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}