{
 "title": "Dashboard Application DB",
 "time": { "from": "2026-03-14T07:06:37.425Z", "to": "2026-03-14T07:10:32.347Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Application Ready Seconds AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(application_ready_time_seconds{instance=\"calc-application-db:8081\", job=\"calc-application-db\", main_application_class=\"com.trevisan.CalculadoraMicroServicesDB.CalculadoraMicroServicesDbApplication\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(process_cpu_usage{instance=\"calc-application-db:8081\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Requests Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(sum by() (rate(http_server_requests_active_seconds_count{instance=\"calc-application-db:8081\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JDBC Connections Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jdbc_connections_active{instance=\"calc-application-db:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"calc-application-db:8081\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikari Connections Pendings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_pending{instance=\"calc-application-db:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikari Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"calc-application-db:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault Token Expire Register",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "vault_expire_register_auth_sum{instance=\"vault-calc:8200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network receive Vault %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total{instance=\"vault-calc:8200\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}