{
 "title": "Status Application",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Sum restart total containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(__name__) (changes(container_start_time_seconds{job=\"cadvisor-service\", name=~\"calc-application-db|grafana-monitor|prometheus-monitor|mysql-calc|vault-calc|cadvisor-monitor\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last return of Mysql",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(up{job=\"mysql-calc\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{alias=\"cadvisor-service\"}) / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last return of Application",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(up{job=\"calc-application-db\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql - Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "up{instance=\"mysql-exporter:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last return of Vault",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(up{job=\"vault-calc\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application - Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "up{instance=\"calc-application-db:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault - Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "up{instance=\"vault-calc:8200\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}