global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'calc-application-db'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['calc-application-db:8081']

  - job_name: 'vault-calc'
    metrics_path: '/v1/sys/metrics'
    scrape_interval: 5s
    params:
      format: ['prometheus']
    bearer_token: 'vault-root-token'
    static_configs:
      - targets: ['vault-calc:8200']

  - job_name: 'mysql-calc'
    scrape_interval: 5s
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'cadvisor-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor-service:8082']
        labels:
          alias: "cadvisor-service"

  - job_name: 'calc-application-main'
    metrics_path: '/acuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['calc-app-main:8083']